### ISSUE TITLE
Several "Can't parse" errors - possibly due to f-strings

### ISSUE THREAD

**Issue by miker985** [kensho-technologies/pytest-annotate#5]
Using the annotation (`pytest --annotate-output=./annotations.json`) worked fine

But when I ran `pyannotate` I got several errors ala `Can't parse ./winnower/util/path.py: ParseError: bad input: type=3, value="'Path {orig_path} is not vaid. Component {piece!r}'", context=('', (32, 24))`

Does this support f-strings?

**Comment by obi1kenobi** [comment]
Hi @miker985, thank you for checking out this project and I'm sorry to hear you ran into a problem.

Could you check the following things:
- What python version are the `pytest` / `pytest-annotate` / `pyannotate` packages installed under?
- What python version is the input program you are trying to annotate intended to be?

What I'm specifically trying to check for here is annotating a Python 3 program with tools that were installed in Python 2 and therefore don't yet understand f-strings and other Python 3 syntax. If that is the case, installing `pytest` / `pytest-annotate` / `pyannotate` under Python 3 (which they all support) should be the first step and may solve the problem entirely.

If that isn't the case, it would help a lot if you could:
- Post the full error including stack trace that you are getting.
- Post the generated annotations file that `pytest-annotate` produced.
- Post the Python file that had the parsing error.

That way I can work to reproduce the problem locally and help you resolve it.

**Comment by miker985** [comment]
* pytest 3.7.2
* pytest-annotate 1.0.2
* pyannotate 1.0.6

The input program is 3.6 and 3.7 compatible.(f-strings added in 3.6). The python version is `Python 3.6.1 :: Continuum Analytics, Inc.` (I use miniconda/Anaconda) and all the pytest/pyannotate things were installed via `pip` using that 3.6.1 environment.

52 files had errors, so I'm sending the smallest one + annotations + related tests. I was able to reproduce behavior using just these 3 files.

```
$ pytest --annotate-output=path-output.json && pyannotate --type-info=path-output.json .
================================================ test session starts ================================================
platform darwin -- Python 3.6.1, pytest-3.7.2, py-1.5.3, pluggy-0.7.1
rootdir: /Users/miker985/tmp/annotate, inifile:
plugins: xdist-1.17.1, profiling-1.2.11, cov-2.5.1, annotate-1.0.2
collected 2 items

test_path.py s.                                                                                               [100%]

======================================== 1 passed, 1 skipped in 0.30 seconds ========================================
Can't parse ./path.py: ParseError: bad input: type=3, value="'Path {orig_path} is not vaid. Component {piece!r}'", context=('', (32, 24))
No files need to be modified.
There was 1 error:
Can't parse ./path.py: ParseError: bad input: type=3, value="'Path {orig_path} is not vaid. Component {piece!r}'", context=('', (32, 24))
NOTE: this was a dry run; use -w to write files
```

Thank you for your help!

[FileTestAnnotation.zip](https://github.com/kensho-technologies/pytest-annotate/files/2361487/FileTestAnnotation.zip)

**Comment by obi1kenobi** [comment]
Thank you -- I'll look into it over the next few days and get back to you.

**Comment by obi1kenobi** [comment]
Could you include the output of `pip freeze` in that environment? Also, could you try running `hash -r` in your shell to reset any cached PATH entries, and then re-run the `pyannotate` command?

My best guess right now is that `pyannotate` might be installed under a different Python version, and its lookup might be cached in the shell's PATH hashtable. This is because I was unable to reproduce the problem -- here's what I get instead, in a fresh py3 environment:

```
$ pyannotate --type-info ./path-output.json path.py 
Refactored path.py
--- path.py	(original)
+++ path.py	(refactored)
@@ -2,6 +2,7 @@
 from pathlib import Path
 import platform
 import sys
+from pathlib import PosixPath
 
 # from winnower import errors
 
@@ -42,6 +43,7 @@
 
 
 def J_drive():
+    # type: () -> PosixPath
     """
     Return path to /snfs1 AKA the J: drive.
     """
Files that need to be modified:
path.py
NOTE: this was a dry run; use -w to write files
```

**Comment by miker985** [comment]
```
$ pip freeze
alabaster==0.7.10
apipkg==1.4
appdirs==1.4.3
argh==0.26.2
astroid==1.6.5
atomicwrites==1.1.5
attrs==18.1.0
Babel==2.5.3
black==18.5b0
boltons==17.1.0
certifi==2018.1.18
chardet==3.0.4
click==6.7
colorama==0.3.7
coverage==4.4.1
docopt==0.6.2
docutils==0.14
execnet==1.4.1
flake8==3.3.0
gprof2dot==2016.10.13
idna==2.6
imagesize==1.0.0
isort==4.3.4
Jinja2==2.10
lazy-object-proxy==1.3.1
MarkupSafe==1.0
mccabe==0.6.1
more-itertools==4.1.0
mypy-extensions==0.4.1
mysqlclient==1.3.12
numpy==1.13.3
packaging==17.1
pandas==0.23.1
pathtools==0.1.2
pluggy==0.7.1
py==1.5.3
pyannotate==1.0.6
pycodestyle==2.3.1
pyflakes==1.5.0
Pygments==2.2.0
pylint==1.9.2
pyparsing==2.2.0
pytest==3.7.2
pytest-annotate==1.0.2
pytest-cov==2.5.1
pytest-cover==3.0.0
pytest-coverage==0.0
pytest-profiling==1.2.11
pytest-watch==4.1.0
pytest-xdist==1.17.1
python-dateutil==2.6.1
pytz==2017.3
PyYAML==3.12
requests==2.18.4
savReaderWriter==3.4.2
simpledbf==0.2.6
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.7.1
sphinx-rtd-theme==0.2.4
sphinxcontrib-websupport==1.0.1
SQLAlchemy==1.1.5
urllib3==1.22
versioneer==0.18
watchdog==0.8.3
-e git+ssh://git@stash.ihme.washington.edu:7999/~miker985/winnower.git@fc66c0a8786a22c0562d4e8c4111015291bba86b#egg=winnower
wrapt==1.10.11
xlrd==1.0.0
```

```
$ hash -r; pytest --annotate-output=path-output.json && pyannotate --type-info=path-output.json .
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.6.1, pytest-3.7.2, py-1.5.3, pluggy-0.7.1
rootdir: /Users/miker985/tmp/annotate, inifile:
plugins: xdist-1.17.1, profiling-1.2.11, cov-2.5.1, annotate-1.0.2
collected 2 items

test_path.py s.                                                                                                                                        [100%]

============================================================ 1 passed, 1 skipped in 0.08 seconds =============================================================
Can't parse ./path.py: ParseError: bad input: type=3, value="'Path {orig_path} is not vaid. Component {piece!r}'", context=('', (30, 24))
No files need to be modified.
There was 1 error:
Can't parse ./path.py: ParseError: bad input: type=3, value="'Path {orig_path} is not vaid. Component {piece!r}'", context=('', (30, 24))
NOTE: this was a dry run; use -w to write files
```

**Please note** that using an entirely new environment I no longer get the parse error. I think something may have gone awry in my conda environment

**Comment by obi1kenobi** [comment]
Interesting -- glad you were able to find a way to not get the parse error. This seems to match the Python environment / version error hypothesis.

Since the `pytest-annotate` plugin produced a valid output JSON file which `pyannotate` in your new environment was able to read, I don't think this is a bug in `pytest-annotate` so I will mark the issue resolved.
